### ISSUE TITLE
Galacticraft Compatibility

### ISSUE THREAD

**Issue by joshmackey** [ganymedes01/ErebusIssueTracker#23]
````
java.lang.ClassCastException: micdoodle8.mods.galacticraft.core.world.gen.BiomeGenFlatMoon cannot be cast to erebus.world.biomes.BiomeBaseErebus
        at erebus.world.genlayer.GenLayerSubBiomes.func_75904_a(GenLayerSubBiomes.java:42)
        at net.minecraft.world.gen.layer.GenLayerZoom.func_75904_a(SourceFile:20)
        at net.minecraft.world.gen.layer.GenLayerZoom.func_75904_a(SourceFile:20)
        at net.minecraft.world.gen.layer.GenLayerZoom.func_75904_a(SourceFile:20)
        at net.minecraft.world.gen.layer.GenLayerZoom.func_75904_a(SourceFile:20)
        at net.minecraft.world.gen.layer.GenLayerVoronoiZoom.func_75904_a(SourceFile:23)
        at erebus.world.WorldChunkManagerErebus.func_76931_a(WorldChunkManagerErebus.java:111)
        at net.minecraft.world.biome.BiomeCache$Block.<init>(SourceFile:27)
        at net.minecraft.world.biome.BiomeCache.func_76840_a(SourceFile:52)
        at net.minecraft.world.biome.BiomeCache.func_76837_b(SourceFile:61)
        at erebus.world.WorldChunkManagerErebus.func_76935_a(WorldChunkManagerErebus.java:43)
        at tconstruct.world.gen.TBaseWorldGenerator.generateSurface(TBaseWorldGenerator.java:60)
````

Not sure why it happened. I woke up to find the server had crashed. I don't believe anyone was active at the time.

**Comment by chylex** [comment]
It happened because you can't just throw a mod into a folder and expect it to perfectly work with other mods. You have conflicting biome IDs with galacticraft, which uses IDs around 102-105.
