### ISSUE TITLE
Water Striders cause crash when walking on water in MP

### ISSUE THREAD

**Issue by krwminer** [ganymedes01/ErebusIssueTracker#26]
Here is the crash report:

[19:36:56] [Server thread/INFO]: Starting minecraft server version 1.7.10
[19:37:06] [Server thread/INFO]: Loading properties
[19:37:06] [Server thread/INFO]: Default game type: SURVIVAL
[19:37:06] [Server thread/INFO]: Generating keypair
[19:37:07] [Server thread/INFO]: Starting Minecraft server on 0.0.0.0:25565
[19:37:08] [Server thread/INFO]: Preparing level "Erebus"
[19:37:09] [Server thread/INFO]: Preparing start region for level 0
[19:37:10] [Server thread/INFO]: Preparing spawn area: 28%
[19:37:11] [Server thread/INFO]: Done (2.822s)! For help, type "help" or "?"
[19:37:37] [User Authenticator #1/INFO]: UUID of player krwminer is c657219e-36ba-495c-aff4-dad3c248f76c
[19:37:38] [Server thread/INFO]: krwminer[/192.168.2.1:50546] logged in with entity id 93 at (-962.6921308476636, 64.0, 616.8663700814757)
[19:37:38] [Server thread/INFO]: krwminer joined the game
[19:37:56] [Server thread/INFO]: [krwminer: Set own game mode to Creative Mode]
[19:38:48] [Server thread/WARN]: Failed to handle packet for /192.168.2.1:50546
net.minecraft.util.ReportedException: Ticking player
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:349) ~[mw.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:303) ~[nh.class:?]
	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:137) ~[jd.class:?]
	at net.minecraft.network.play.client.C03PacketPlayer$C04PacketPlayerPosition.func_148833_a(SourceFile:63) ~[je.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft
	at erebus.item.WaterStriders.onArmorTick(WaterStriders.java:45) ~[WaterStriders.class:?]
	at net.minecraft.entity.player.InventoryPlayer.func_70429_k(InventoryPlayer.java:319) ~[yx.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:538) ~[yz.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1609) ~[sv.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:288) ~[yz.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:295) ~[mw.class:?]
	... 10 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.Minecraft
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_65]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_65]
	at erebus.item.WaterStriders.onArmorTick(WaterStriders.java:45) ~[WaterStriders.class:?]
	at net.minecraft.entity.player.InventoryPlayer.func_70429_k(InventoryPlayer.java:319) ~[yx.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:538) ~[yz.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1609) ~[sv.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:288) ~[yz.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:295) ~[mw.class:?]
	... 10 more
Caused by: java.lang.RuntimeException: Attempted to load class bao for invalid side SERVER
	at cpw.mods.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:50) ~[forge1710_1230.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_65]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_65]
	at erebus.item.WaterStriders.onArmorTick(WaterStriders.java:45) ~[WaterStriders.class:?]
	at net.minecraft.entity.player.InventoryPlayer.func_70429_k(InventoryPlayer.java:319) ~[yx.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:538) ~[yz.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1609) ~[sv.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:288) ~[yz.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:295) ~[mw.class:?]
	... 10 more
[19:38:49] [Server thread/INFO]: krwminer lost connection: TextComponent{text='Internal server error', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}}
[19:38:49] [Server thread/INFO]: krwminer left the game

Let me know if you have any questions.

**Comment by vadis365** [comment]
I hope this is now fixed....
